// File written 2018 by Erik Flink
// Some code authored 2015 by Axel Isaksson

#include <pic32mx.h>
#include <stdint.h>
#include <stdbool.h>

#define OLED_WIDTH 128
#define OLED_HEIGHT 64
#define OLED_ADDRESS 0x78
#define CONTROL_BYTE_D 0xC0
#define CONTROL_BYTE_C 0x80
#define CONTROL_BYTE_ONLYDATA 0x40

char display_buffer[OLED_HEIGHT / 8][OLED_WIDTH];

// Turns off all pixels in buffer
// Authored by Erik Flink
void clear_buffer() {
  int y = 0;
  int x = 0;
  for (y = 0; y < (OLED_HEIGHT / 8); y++) {
    for (x = 0; x < OLED_WIDTH; x++) {
      display_buffer[y][x] = 0x00;
    }
  }
}

// Turns on pixel with (x, y) coordinates in buffer
// Authored by Erik Flink
void set_pixel(int x, int y) {
  display_buffer[y / 8][x] = display_buffer[y / 8][x] | 1 << (y % 8);
}

// Turns off pixel with (x, y) coordinates in buffer
// Authored by Erik Flink
void clear_pixel(int x, int y) {
  display_buffer[y / 8][x] = display_buffer[y / 8][x] & ~(1 << (y % 8));
}

// Following code authored by Axel Isaksson
// Copied from hello-temperature project

void i2c_setup() {
  /* Set up i2c */
	I2C1CON = 0x0;
	/* I2C Baud rate should be less than 400 kHz, is generated by dividing
	the 40 MHz peripheral bus clock down */
	I2C1BRG = 0x0C2;
	I2C1STAT = 0x0;
	I2C1CONSET = 1 << 13; //SIDL = 1
	I2C1CONSET = 1 << 15; // ON = 1
}

/* Wait for I2C bus to become idle */
void i2c_idle() {
	while(I2C1CON & 0x1F || I2C1STAT & (1 << 14)); //TRSTAT
}

/* Send one byte on I2C bus, return ack/nack status of transaction */
bool i2c_send(uint8_t data) {
	i2c_idle();
	I2C1TRN = data;
	i2c_idle();
	return !(I2C1STAT & (1 << 15)); //ACKSTAT
}

/* Receive one byte from I2C bus */
uint8_t i2c_recv() {
	i2c_idle();
	I2C1CONSET = 1 << 3; //RCEN = 1
	i2c_idle();
	I2C1STATCLR = 1 << 6; //I2COV = 0
	return I2C1RCV;
}

/* Send acknowledge conditon on the bus */
void i2c_ack() {
	i2c_idle();
	I2C1CONCLR = 1 << 5; //ACKDT = 0
	I2C1CONSET = 1 << 4; //ACKEN = 1
}

/* Send not-acknowledge conditon on the bus */
void i2c_nack() {
	i2c_idle();
	I2C1CONSET = 1 << 5; //ACKDT = 1
	I2C1CONSET = 1 << 4; //ACKEN = 1
}

/* Send start conditon on the bus */
void i2c_start() {
	i2c_idle();
	I2C1CONSET = 1 << 0; //SEN
	i2c_idle();
}

/* Send restart conditon on the bus */
void i2c_restart() {
	i2c_idle();
	I2C1CONSET = 1 << 1; //RSEN
	i2c_idle();
}

/* Send stop conditon on the bus */
void i2c_stop() {
	i2c_idle();
	I2C1CONSET = 1 << 2; //PEN
	i2c_idle();
}

// End of copied code

// Sends specified command byte to OLED-display
// Derived from code written by Axel Isaksson
// Edited by Erik Flink
void oled_command(uint8_t command) {
  /* Send start condition and address of the temperature sensor with
	write mode (lowest bit = 0) until the temperature sensor sends
	acknowledge condition */
	do {
		i2c_start();
	} while(!i2c_send(OLED_ADDRESS));
	/* Send control byte followed by command */
	i2c_send(CONTROL_BYTE_C);
	i2c_send(command);
	/* Send stop condition */
	i2c_stop();
}

// Sends specified data byte to OLED-display
// Derived from code written by Axel Isaksson
// Edited by Erik Flink
void oled_data(uint8_t data) {
  /* Send start condition and address of the temperature sensor with
	write mode (lowest bit = 0) until the temperature sensor sends
	acknowledge condition */
	do {
		i2c_start();
	} while(!i2c_send(OLED_ADDRESS));
	/* Send control byte followed by command */
	i2c_send(CONTROL_BYTE_D);
	i2c_send(data);
	/* Send stop condition */
	i2c_stop();
}

// Initiates oled display by sending appropriate commands
// Authored by Erik Flink
void oled_init() {
  i2c_setup();

  // Set MUX
  oled_command(0xA8);
  oled_command(0x3F);

  // Set display offset
  oled_command(0xD3);
  oled_command(0x00);

  // Set display start line
  oled_command(0x40);

  // Set segment re-map
  oled_command(0xA0);

  // Set COM output scan direction
  oled_command(0xC0);

  // Set COM pins hardware configuration
  oled_command(0xDA);
  oled_command(0x12);

  // Set contrast control
  oled_command(0x81);
  oled_command(0x7F);

  // Disable entire display on
  oled_command(0xA4);

  // Set normal display
  oled_command(0xA6);

  // Set osc frequency
  oled_command(0xD5);
  oled_command(0x80);


  // Set memory addressing mode
  oled_command(0x20);
  oled_command(0x00);


  // Enable charge pump regulator
  oled_command(0x8D); // Charge pump setting
  oled_command(0x14); // Enable charge pump

  oled_command(0xAF); // Power ON
}

// Sends command to set entire display on
// Used for debugging
// Authored by Erik Flink
void set_entire_display_on() {
  oled_command(0xA5); // Turn entire display on
}

// Sends entire buffer to display
// Authored by Erik Flink
// Derived from code written by Axel Isaksson
void oled_update() {
  // Place pointer at (0,0)
  oled_command(0x21);
  oled_command(0);
  oled_command(127);

  oled_command(0x22);
  oled_command(0);
  oled_command(7);

  /* Send start condition and address of the temperature sensor with
	write mode (lowest bit = 0) until the temperature sensor sends
	acknowledge condition */
	do {
		i2c_start();
	} while(!i2c_send(OLED_ADDRESS));
	/* Send control byte followed by command */
	i2c_send(CONTROL_BYTE_ONLYDATA);

  int y = 0;
  int x = 0;
  for (y = 0; y < (OLED_HEIGHT / 8); y++) {
    for (x = 0; x < OLED_WIDTH; x++) {
      i2c_send(display_buffer[y][x]);
    }
  }

	/* Send stop condition */
	i2c_stop();
}
